name: Build and release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel setuptools

      - name: Build frontend and wheel
        run: |
          chmod +x scripts/build_release.sh
          bash scripts/build_release.sh

      - name: Run backend tests
        run: |
          python -m pip install -r backend/requirements-dev.txt
          pytest -q

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-dist
          path: dist/